name: Defender File Scanner Resources
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - deployabletemplates/malwarescanner
    exclude:
      - azure-pipelines-*.yml
variables:
pool:
  vmImage: windows-latest
stages:
  - stage: NonProd_MalwareScannerResourcesDeployment
    jobs:
      - deployment: NonProd_MalwareScannerResourcesDeployment
        displayName: "Deploy Malware Scanner PPE Resources to Azure"
        environment: $(PreProd_CommonEnvironment)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  clean: true
                - task: AzureCLI@2
                  displayName: "deploy common bicep template"
                  inputs:
                    azureSubscription: $(PreProd_AzureSubscriptionName)
                    scriptType: "pscore"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      az deployment group create  `
                      --template-file $(Build.SourcesDirectory)/deployabletemplates/commonResources/common.bicep `
                      --parameters $(Build.SourcesDirectory)/deployabletemplates/commonResources/parameters/common-westus2.parameters.json `
                      --resource-group $(PreProd_CommonResourceGroupName)
                - task: AzureCLI@2
                  displayName: "deploy bicep template"
                  inputs:
                    azureSubscription: $(PreProd_AzureSubscriptionName)
                    scriptType: "pscore"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      az deployment group create  `
                      --template-file $(Build.SourcesDirectory)/deployabletemplates/malwarescanner/malwarescanner-ppe.bicep `
                      --parameters $(Build.SourcesDirectory)/deployabletemplates/malwarescanner/parameters/malwarescanner-ppe.parameters.json `
                      --resource-group $(PreProd_CommonResourceGroupName)